In [1]:
import seaborn as sns
import numpy as np
import pandas as pd

In [4]:
df = sns.load_dataset('titanic')

In [6]:
dummay_df = pd.get_dummies(df)

In [7]:
dummay_df

,survived,pclass,age,sibsp,parch,fare,adult_male,alone,sex_female,sex_male,...,deck_C,deck_D,deck_E,deck_F,deck_G,embark_town_Cherbourg,embark_town_Queenstown,embark_town_Southampton,alive_no,alive_yes
0,0,3,22.0,1,0,7.2500,True,False,False,True,...,False,False,False,False,False,False,False,True,True,False
1,1,1,38.0,1,0,71.2833,False,False,True,False,...,True,False,False,False,False,True,False,False,False,True
2,1,3,26.0,0,0,7.9250,False,True,True,False,...,False,False,False,False,False,False,False,True,False,True
3,1,1,35.0,1,0,53.1000,False,False,True,False,...,True,False,False,False,False,False,False,True,False,True
4,0,3,35.0,0,0,8.0500,True,True,False,True,...,False,False,False,False,False,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,27.0,0,0,13.0000,True,True,False,True,...,False,False,False,False,False,False,False,True,True,False
887,1,1,19.0,0,0,30.0000,False,True,True,False,...,False,False,False,False,False,False,False,True,False,True
888,0,3,NaN,1,2,23.4500,False,False,True,False,...,False,False,False,False,False,False,False,True,True,False
889,1,1,26.0,0,0,30.0000,True,True,False,True,...,True,False,False,False,False,True,False,False,False,True
890,0,3,32.0,0,0,7.7500,True,True,False,True,...,False,False,False,False,False,False,True,False,True,False

In [ ]:
pd.DataFrame()

In [42]:
dic = {
    'sex':['male','female','female','male','female',np.nan,'']
}

In [43]:
df1 = pd.DataFrame(dic)

In [44]:
df1

      sex
0    male
1  female
2  female
3    male
4  female
5     NaN
6

In [45]:
pd.get_dummies(df1)

    sex_  sex_female  sex_male
0  False       False      True
1  False        True     False
2  False        True     False
3  False       False      True
4  False        True     False
5  False       False     False
6   True       False     False

In [37]:
df1.sex.value_counts()

sex
female    3
male      2
          1
Name: count, dtype: int64